-- Applied 2026-10-04. Additive/idempotent. Rollback: drop the added columns, reserves + reserve_contributions, the indexes and avatar policies.
alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists currency text default 'UGX';
alter table public.profiles add column if not exists locale text default 'en-UG';
alter table public.profiles add column if not exists onboarding_done boolean default false;
alter table public.profiles add column if not exists notifications jsonb default '{}'::jsonb;
alter table public.budgets add column if not exists start_date date;
alter table public.budgets add column if not exists end_date date;
alter table public.budgets add column if not exists icon text;
alter table public.budgets add column if not exists color text;
alter table public.planned_categories add column if not exists icon text;
alter table public.planned_categories add column if not exists color text;
alter table public.expenses add column if not exists updated_at timestamptz default now();
create table if not exists public.reserves (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), name text not null, target_amount numeric(14,2) not null check (target_amount > 0), target_date date, icon text, color text, archived boolean default false, created_at timestamptz default now());
create table if not exists public.reserve_contributions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), reserve_id uuid not null references public.reserves on delete cascade, amount numeric(14,2) not null check (amount <> 0), note text, contributed_on date default current_date, created_at timestamptz default now());
alter table public.reserves enable row level security;
alter table public.reserve_contributions enable row level security;
drop policy if exists "own rows" on public.reserves;
create policy "own rows" on public.reserves for all using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "own rows" on public.reserve_contributions;
create policy "own rows" on public.reserve_contributions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create index if not exists expenses_budget_spent_idx on public.expenses (budget_id, spent_on desc);
create index if not exists expenses_user_created_idx on public.expenses (user_id, created_at desc);
create index if not exists planned_categories_budget_idx on public.planned_categories (budget_id);
create index if not exists reserve_contrib_reserve_idx on public.reserve_contributions (reserve_id);
drop policy if exists "avatar update own" on storage.objects;
create policy "avatar update own" on storage.objects for update to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "avatar delete own" on storage.objects;
create policy "avatar delete own" on storage.objects for delete to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);
